version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15673:15673"
    networks:
      - net
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    volumes:
      - ./conf:C:\rabbitmq\conf
      - rabbitmq_db:c:\rabbitmq\data\db
      - rabbitmq_logs:c:\rabbitmq\data\log
    environment:
      - RABBITMQ_CONFIG_FILE=C:\rabbitmq\conf\rabbitmq.conf

volumes:
  rabbitmq_db:
  rabbitmq_logs:

networks:
  net:
